= zsh-trampoline

== Quick start

. Install the requirements listed in <<Requirements>>.
. Follow the instructions in the section <<Installation>>.
. Add your configuration file as described in <<Configuration>>.

== Requirements

* https://www.gnu.org/software/gawk/[Gawk] 4.1 or newer.
* A recent version of https://github.com/junegunn/fzf[fzf].
* Zsh as your shell (of course).

On macOS, the requirements can be installed using https://brew.sh/[Homebrew]:

[source,shell]
----
brew install gawk fzf
----

== Installation

To download and source the plugin, use your favorite plugin manager. For example, use
https://github.com/rossmacarthur/sheldon[Sheldon]:

[source,toml]
----
# ~/.config/sheldon/plugins.toml

[plugins.poc-zsh-plugin]
github = "HerCerM/zsh-trampoline"
----

The plugin provides two Zsh functions for setup which are meant to be called in the
`.zshrc`. Only one function needs to be called depending on the following criteria:

. `zt_setup_widget_jump_to_directory`: When _not_ using the plugin
  https://github.com/jeffreytse/zsh-vi-mode[zsh-vi-mode].
. `zt_zvm_setup_widget_jump_to_directory`: When using the plugin zsh-vi-mode.

In case of using the second function, do the call inside of `zvm_after_init`, like this:

[source,bash]
----
function zvm_after_init {
  # In insert mode, press 'ctrl+j' to cd to a directory.
  zt_zvm_setup_widget_jump_to_directory
}
----

++++
<table><tr>
<td>
ℹ️
</td>
<td>
When using either the first or the second function, do the call <i>after</i> the
zsh-trampoline plugin is sourced. For example, for Sheldon that is after
<code>eval "$(sheldon source)"</code>.
</td>
</tr></table>
++++

== Configuration

The configuration for zsh-trampoline is provided in two places:

. A CSV configuration file.
. Environment variables.

=== 1. Configuration file `config.csv`

This CSV file is searched in the directory `$XDG_CONFIG_HOME/zt`. As a fallback, it's
searched in `~/.config/zt` when the environment variable `$XDG_CONFIG_HOME` is not set.
The row format of the file is as shown below. Conceptually, each row represents a
directory that can be jumped to, and each directory can have metadata associated with it.

[source]
----
{path}, {description}, {expand}
|____|  |_____________________|
 \       \
  \       \__ metadata
   \
    \__ directory
----

|===
|Column |Required |Description

| `{path}` | Yes
| Relative or absolute path to a directory. Environment variables and the caret symbol
(`~`) are recognized.

| `{description}` | No
| Short one-line description of the directory. Must not contain a comma (`,`).

| `{expand}` | No
| Whether to list all level-1 subdirectories. To enable set to `true`.
|===

Example of valid contents of a file `~/.config/zt/config.csv`. Notice that spaces for
padding are allowed, but are not required.

[source,csv]
----
~/dev/gc                      ,Git cloned repos not mine.  ,true
~/dev/temp                    ,Temporary files.
~/.local/share/sheldon/repos
----

In addition to `config.csv`, a second file can be provided following the same format,
`config_local.csv`. When listing the directories to select a jump location, the
contents of the latter file may be appended to the former file.

=== 2. Environment variables

|===
| Environment variable | Allowed values | Default value | Description

| `ZT_DIRECTORY_DECORATOR` | Single character | `*`
| Prefix of the `{path}` for every row in the CSV config files. This eases selection
through fzf by allowing to exclude the expanded directories.

| `ZT_LIST_DIRECTORIES_LOCAL` | `0` or `1` | `1`
| Whether to list directories listed in `config_local.csv`. By default, all directories
are listed.

| `ZT_KEY_MAP_JUMP_TO_DIRECTORY`
| https://github.com/rothgar/mastering-zsh/blob/master/docs/helpers/bindkey.md[
`bindkey` key map] | `^j`
| Key sequence to press to list directories in fzf. By default, it's
+++<kbd>ctrl+j</kbd>+++.
|===
