#!/bin/zsh

## Print only the files listed explicitly in ZT_CONFIG.
## @param $1 ZT_CONFIG serialization file, which content is the output of `typeset -p ZT_CONFIG`.

source "${1}"

## @param $@ Items from the parameter ZT_CONFIG.
## @stdout Files without options.
for raw_file in ${ZT_CONFIG}; do
  echo "${raw_file%%:*}" | sed "s#${HOME}#~#"
done
