#!/bin/zsh

## @param $@ Items from the parameter ZT_CONFIG.
## @stdout Files without options. Options are applied to build stdout.
for raw_file in ${@}; do
  local file_path="${raw_file%%:*}"
  if [[ -f ${file_path} ]] || [[ ${raw_file[(i):0]} -le ${#raw_file} ]]; then
    echo "${file_path}" | sed "s#${HOME}#~#"
  else
    find "${(e)${file_path}/[~]/${HOME}}" -maxdepth 1 -type d \
      | sed 1d | sed "s#${HOME}#~#" | sort | xargs printf "%s\n"
  fi
done
