format = '''$directory$git_branch
> '''

add_newline = true

[directory]
format = '[$path]($style) '
truncate_to_repo = false
truncation_length = 50

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ''
